### ISSUE TITLE
Add Travis information to master branch

### ISSUE THREAD

**Issue by jeyvison** [mvc-spec/ozark#138]
Master branch is broken. The **MvcContextImpl** does not implement 
URI uri(String identifier,List<Object> params)  as it's defined by the interface. We should add a build status to the project README informing the health of the build.

PS: I don't know if MvcContextImpl is supposed to implement this method or if it should be removed from the interface. If any of you can tell me, i'll submit a pull request.

**Comment by lefloh** [comment]
Build status is green: https://travis-ci.org/mvc-spec/ozark/builds

Ozark-core depends on a snapshot version of mvc-api and I'm not sure if these snapshots are published to maven central. If you're facing issues during local development please try to update and build the [mvc-spec API](https://github.com/mvc-spec/mvc-spec) first.

+1 for adding the build status to the README.md

**Comment by jeyvison** [comment]
Hey @lefloh . All i did was clone the repository and try to compile ozark-core. I'll compile the api and try to use it as dependency instead of the maven dependency defined in POM. Maybe we should update the newest version of the dependency to Maven central and update it in Ozark-core.

I'll make a pull-request for adding to build status to Readme

**Comment by chkal** [comment]
The spec snapshots are automatically deployed to the Sonatype OSS repository which available here:

https://oss.sonatype.org/content/repositories/snapshots/

Ozark is using the latest snapshots of the spec. 

See: 
https://github.com/mvc-spec/ozark/blob/28c6725c87e3f9778d0e80db5c0f2032c007339f/pom.xml#L38

And:
https://github.com/mvc-spec/ozark/blob/28c6725c87e3f9778d0e80db5c0f2032c007339f/core/pom.xml#L108-L113

But you may have to add the snapshots repo to your `settings.xml` so that Maven can fetch the latest snapshots if you build Ozark. But manually building the spec jar will also work. ;-)

**Comment by chkal** [comment]
I'll close this one as #139 has been merged!
