### ISSUE TITLE
Problems with redirection in index.jsp

### ISSUE THREAD

**Issue by CoSoCo** [mvc-spec/ozark#146]
Hi,

I was participant at the JVM-Con 2017-11-29 MVC-1.0 workshop.

Thanks to Ivar :-)

Please see my NetBeans example project in the attachment.
[MVC-1.0_Demo.zip](https://github.com/mvc-spec/ozark/files/1531319/MVC-1.0_Demo.zip)

So far it works fine when starting with the Run-button in the NetBeans 8.2 IDE.

 But when I set ...
- In ApplicationConfig.java
    @ApplicationPath("/")
- In index.jsp
    response.sendRedirect(request.getContextPath() + "/hello?name=Duke");

... I am redirected to http://localhost:8080 instead to http://localhost:8080/hello?name=Duke

What's going wrong here?

Regards,

Ulf

Sorry for posting the question here, but when trying to post to MVC 1.0 Users Mailing List at Google Groups I got an unspecified error multiple times.

**Comment by chkal** [comment]
Hey @CoSoCo,

I hope you liked our workshop. :-)

Just to confirm: So you say the app works with an application path of `/app` but doesn't work with an application path of `/`?

If this is the case, it may actually be a Jersey issue. Not sure about all the details, but if I remember correctly, someone wrote back then, that Jersey doesn't work well with an application path of `/`. Not sure if other JAX-RS implementations handle it better to be honest.

**Comment by CoSoCo** [comment]
Yes exactly. Other arbitrary paths like "/test" also work fine. 
The application itself is working, when I manually browse to http://localhost:8080/hello?name=Duke
, but the redirection doesn't work.
If it's an Jersey issue, I assume, the response.sendRedirect(...) API belongs to Jersey.

**Comment by chkal** [comment]
Ah, I think I know what is happening here.

If you use an application path of `/`, ALL requests will be intercepted and processed by Jersey. Even the request to `http://localhost:8080/` which is actually forwarded to `http://localhost:8080/index.jsp`. Therefore your JSP never is executed and so the redirect doesn't happen.

I just looked up the original issue I was talking about. Here it is: mvc-spec/mvc-spec#44

So from the comments it looks like you can work around this issue if you manually register Jersey as a filter instead of relying on the automatic registration of the Jersey as a servlet. I never tried that, but

**Comment by chkal** [comment]
Any news on this one? If my assumption about the cause is true, this is more a JAX-RS implementation issue. Therefore, I would like to close this one.

**Comment by CoSoCo** [comment]
I don't have the sample project data any more, so can't test it.
